version: "3.7"
services:
    swagger:
        build:
            dockerfile: Dockerfile
            context: spec
            target: swagger
        ports:
            - 4000:8080
        depends_on:
            - edge
    edge:
        build:
            dockerfile: Dockerfile
            context: edge
        ports:
            - 3000:3000
        environment: 
            - ADDR=http://bastion:8080
            - NODE_ENV=production
            - ELASTIC_APM_SERVICE_NAME=edge
            - ELASTIC_APM_SECRET_TOKEN=knlkjdnfsfdsfd
            - ELASTIC_APM_SERVER_URL=http://apm-server:8200
        depends_on:
            - bastion
            - apm-server
    bastion:
        build:
            dockerfile: Dockerfile
            context: bastion
        ports:
            - 8080:8080
        environment: 
            - ELASTIC_APM_SECRET_TOKEN=knlkjdnfsfdsfd
            - ELASTIC_APM_SERVER_URL=http://apm-server:8200
        depends_on: 
            - core
            - apm-server
        command: [ "/bastion","-endpoint", "core:7000" ]
    core:
        build:
            dockerfile: core/Dockerfile
            context: .
        ports:
            - 7000:7000

    apm-server:
        image: docker.elastic.co/apm/apm-server:7.7.0
        depends_on:
            - elasticsearch
            - kibana
        cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
        cap_drop: ["ALL"]
        ports:
            - 8200:8200
        command: >
            apm-server -e
                -E apm-server.rum.enabled=true
                -E setup.kibana.host=kibana:5601
                -E setup.template.settings.index.number_of_replicas=0
                -E apm-server.kibana.enabled=true
                -E apm-server.kibana.host=kibana:5601
                -E apm-server.secret_token:knlkjdnfsfdsfd
                -E output.elasticsearch.hosts=["elasticsearch:9200"]
        healthcheck:
            interval: 10s
            retries: 12
            test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        environment:
            - bootstrap.memory_lock=true
            - cluster.name=docker-cluster
            - cluster.routing.allocation.disk.threshold_enabled=false
            - discovery.type=single-node
            - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
        ulimits:
            memlock:
                hard: -1
                soft: -1
        ports:
            - 9200:9200
        healthcheck:
            interval: 20s
            retries: 10
            test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

    kibana:
        image: docker.elastic.co/kibana/kibana:7.7.0
        depends_on:
            - elasticsearch
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        ports:
        - 5601:5601
        healthcheck:
            interval: 10s
            retries: 20
            test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status
